INSERT INTO BEER (name) VALUES ('Abbaye des Roc');
INSERT INTO BEER (name) VALUES ('Achel 8 Blon');
INSERT INTO BEER (name) VALUES ('Achel 8 Brui');
INSERT INTO BEER (name) VALUES ('Adriaen Brouwe');
INSERT INTO BEER (name) VALUES ('Adriaen Brouwer Oake');
INSERT INTO BEER (name) VALUES ('Adriaen Brouwer Tripe');
INSERT INTO BEER (name) VALUES ('Affligem Tripe');
INSERT INTO BEER (name) VALUES ('Arabie');
INSERT INTO BEER (name) VALUES ('Ardenne Stou');
INSERT INTO BEER (name) VALUES ('Abbaye de Brogne Brune');
INSERT INTO BEER (name) VALUES ('Abbaye de Brogne Blonde');
INSERT INTO BEER (name) VALUES ('Bacchus Frambozenbier');
INSERT INTO BEER (name) VALUES ('Bacchus Kriekenbier');
INSERT INTO BEER (name) VALUES ('Bacchus Vlaams Oud Bruin');
INSERT INTO BEER (name) VALUES ('Barista');
INSERT INTO BEER (name) VALUES ('Bavik Super Pils');
INSERT INTO BEER (name) VALUES ('Bertinchamps Triple');
INSERT INTO BEER (name) VALUES ('Blanche des Honnelles');
INSERT INTO BEER (name) VALUES ('Bourgogne des Flandres');
INSERT INTO BEER (name) VALUES ('Brasserie LeFort');
INSERT INTO BEER (name) VALUES ('Brigand');
INSERT INTO BEER (name) VALUES ('Brugge Tripel');
INSERT INTO BEER (name) VALUES ('Brugse Zot');
INSERT INTO BEER (name) VALUES ('Brunehaut Saison');
INSERT INTO BEER (name) VALUES ('Bush Ambrée');
INSERT INTO BEER (name) VALUES ('Bush Ambrée Triple');
INSERT INTO BEER (name) VALUES ('Bush Blonde');
INSERT INTO BEER (name) VALUES ('Bush Blonde Triple');
INSERT INTO BEER (name) VALUES ('Bush de Charmes');
INSERT INTO BEER (name) VALUES ('Bush de Noël');
INSERT INTO BEER (name) VALUES ('Bush de Noël Premium');
INSERT INTO BEER (name) VALUES ('Bush de Nuits');
INSERT INTO BEER (name) VALUES ('Boskeun');
INSERT INTO BEER (name) VALUES ('Bastogne Pale Ale');
INSERT INTO BEER (name) VALUES ('Bush Prestige');
INSERT INTO BEER (name) VALUES ('Chimay Bleue (Blue Cap)');
INSERT INTO BEER (name) VALUES ('Chimay Dorée (Gold)');
INSERT INTO BEER (name) VALUES ('Chimay Rouge (Red Cap)');
INSERT INTO BEER (name) VALUES ('Chimay Triple (White Cap)');
INSERT INTO BEER (name) VALUES ('Chouffe Soleil');
INSERT INTO BEER (name) VALUES ('Cornet');
INSERT INTO BEER (name) VALUES ('Cuvée des Jacobins');
INSERT INTO BEER (name) VALUES ('Cuvée des Trolls');
INSERT INTO BEER (name) VALUES ('Cuvée des Trolls Triple');
INSERT INTO BEER (name) VALUES ('Coccinelle');
INSERT INTO BEER (name) VALUES ('Cuvée du Chateau');
INSERT INTO BEER (name) VALUES ('De Koninck');
INSERT INTO BEER (name) VALUES ('Delirium Tremens');
INSERT INTO BEER (name) VALUES ('DeuS Brut des Flandres');
INSERT INTO BEER (name) VALUES ('Diôle Ambrée');
INSERT INTO BEER (name) VALUES ('Diôle Blonde');
INSERT INTO BEER (name) VALUES ('Diôle Brune');
INSERT INTO BEER (name) VALUES ('Double Enghien Blonde');
INSERT INTO BEER (name) VALUES ('Duchesse de Bourgogne');
INSERT INTO BEER (name) VALUES ('Duvel');
INSERT INTO BEER (name) VALUES ('Duvel Tripel Hop Citra');
INSERT INTO BEER (name) VALUES ('Dulle Teve');
INSERT INTO BEER (name) VALUES ('Ename Blond');
INSERT INTO BEER (name) VALUES ('Ename Dubbel');
INSERT INTO BEER (name) VALUES ('Ename Pater');
INSERT INTO BEER (name) VALUES ('Ename Tripel');
INSERT INTO BEER (name) VALUES ('Filou');
INSERT INTO BEER (name) VALUES ('Gentse Strop');
INSERT INTO BEER (name) VALUES ('Goliath Triple');
INSERT INTO BEER (name) VALUES ('Gouden Carolus Classic');
INSERT INTO BEER (name) VALUES ('Green Killer IPA');
INSERT INTO BEER (name) VALUES ('Grotten Santé');
INSERT INTO BEER (name) VALUES ('Gulden Draak');
INSERT INTO BEER (name) VALUES ('Jack''s Precious IPA');
INSERT INTO BEER (name) VALUES ('Gulden Spoor IPA');
INSERT INTO BEER (name) VALUES ('Herkenrode Noctis');
INSERT INTO BEER (name) VALUES ('Herkenrode Vesper Tripel');
INSERT INTO BEER (name) VALUES ('Houblon Chouffe');
INSERT INTO BEER (name) VALUES ('Kasteel Blond');
INSERT INTO BEER (name) VALUES ('Kasteel Donker');
INSERT INTO BEER (name) VALUES ('Kasteel Hoppy');
INSERT INTO BEER (name) VALUES ('Kasteel Rouge');
INSERT INTO BEER (name) VALUES ('Kasteel Tripel');
INSERT INTO BEER (name) VALUES ('Kompel Bovengronds');
INSERT INTO BEER (name) VALUES ('Kriek des Jacobins');
INSERT INTO BEER (name) VALUES ('Kriek Max');
INSERT INTO BEER (name) VALUES ('Kwaremont');
INSERT INTO BEER (name) VALUES ('La Chouffe');
INSERT INTO BEER (name) VALUES ('La Divine');
INSERT INTO BEER (name) VALUES ('La Rulles Triple');
INSERT INTO BEER (name) VALUES ('Liefmans Fruitesse');
INSERT INTO BEER (name) VALUES ('Liefmans Goudenband');
INSERT INTO BEER (name) VALUES ('Liefmans Kriek Brut');
INSERT INTO BEER (name) VALUES ('Limburgse Witte');
INSERT INTO BEER (name) VALUES ('Lindemans Framboise');
INSERT INTO BEER (name) VALUES ('Lindemans Oude Kriek Cuvée René');
INSERT INTO BEER (name) VALUES ('Lupulus Blond');
INSERT INTO BEER (name) VALUES ('Leffe Tripel');
INSERT INTO BEER (name) VALUES ('Leffe Royale Whitbread Golding');
INSERT INTO BEER (name) VALUES ('Leffe Royale Mapuche');
INSERT INTO BEER (name) VALUES ('Leffe Royale Cascade IPA');
INSERT INTO BEER (name) VALUES ('Leffe Rituel 9°');
INSERT INTO BEER (name) VALUES ('Leffe Radieuse');
INSERT INTO BEER (name) VALUES ('Leffe Brune');
INSERT INTO BEER (name) VALUES ('Leffe Blonde');
INSERT INTO BEER (name) VALUES ('La Trouffette Belle d''Été');
INSERT INTO BEER (name) VALUES ('La Binchoise XO');
INSERT INTO BEER (name) VALUES ('La Binchoise Blonde');
INSERT INTO BEER (name) VALUES ('Lupulus Hopera');
INSERT INTO BEER (name) VALUES ('Maredsous Blond');
INSERT INTO BEER (name) VALUES ('Maredsous Bruin');
INSERT INTO BEER (name) VALUES ('Maredsous Tripel');
INSERT INTO BEER (name) VALUES ('Mc Chouffe');
INSERT INTO BEER (name) VALUES ('Moinette Bio');
INSERT INTO BEER (name) VALUES ('OMER. Traditional Blond');
INSERT INTO BEER (name) VALUES ('Orval');
INSERT INTO BEER (name) VALUES ('Oude Gueuze Cuvée René');
INSERT INTO BEER (name) VALUES ('Oerbier');
INSERT INTO BEER (name) VALUES ('Palm');
INSERT INTO BEER (name) VALUES ('Passchendaele');
INSERT INTO BEER (name) VALUES ('Pauwel Kwak');
INSERT INTO BEER (name) VALUES ('Pax Pils');
INSERT INTO BEER (name) VALUES ('Pêche Mel’ Bush');
INSERT INTO BEER (name) VALUES ('Petrus Aged Pale');
INSERT INTO BEER (name) VALUES ('Petrus Aged Red');
INSERT INTO BEER (name) VALUES ('Petrus Blond');
INSERT INTO BEER (name) VALUES ('Petrus Dubbel');
INSERT INTO BEER (name) VALUES ('Petrus Rood Bruin');
INSERT INTO BEER (name) VALUES ('Petrus Tripel');
INSERT INTO BEER (name) VALUES ('Piraat');
INSERT INTO BEER (name) VALUES ('PoppoLou');
INSERT INTO BEER (name) VALUES ('Quintine Blonde');
INSERT INTO BEER (name) VALUES ('Rebelse Strop');
INSERT INTO BEER (name) VALUES ('Rochefort 10');
INSERT INTO BEER (name) VALUES ('Rochefort 6');
INSERT INTO BEER (name) VALUES ('Rochefort 8');
INSERT INTO BEER (name) VALUES ('Rodenbach Alexander');
INSERT INTO BEER (name) VALUES ('Rodenbach Classic');
INSERT INTO BEER (name) VALUES ('Rodenbach Grand Cru');
INSERT INTO BEER (name) VALUES ('Saint-Martin Triple');
INSERT INTO BEER (name) VALUES ('Saison Dupont');
INSERT INTO BEER (name) VALUES ('Scotch de Silly');
INSERT INTO BEER (name) VALUES ('Silly Rouge');
INSERT INTO BEER (name) VALUES ('Sint-Gummarus Tripel');
INSERT INTO BEER (name) VALUES ('Slurfke');
INSERT INTO BEER (name) VALUES ('St. Bernardus Abt 12');
INSERT INTO BEER (name) VALUES ('St. Bernardus Prior 8');
INSERT INTO BEER (name) VALUES ('St. Bernardus Tripel');
INSERT INTO BEER (name) VALUES ('St-Feuillien Blonde');
INSERT INTO BEER (name) VALUES ('St-Feuillien Grand Cru');
INSERT INTO BEER (name) VALUES ('St. Louis Gueuze Fond Tradition');
INSERT INTO BEER (name) VALUES ('St. Louis Kriek Fond Tradition');
INSERT INTO BEER (name) VALUES ('St. Louis Kriek Lambic');
INSERT INTO BEER (name) VALUES ('St. Louis Premium Framboise');
INSERT INTO BEER (name) VALUES ('St. Louis Premium Gueuze');
INSERT INTO BEER (name) VALUES ('St. Louis Premium Kriek');
INSERT INTO BEER (name) VALUES ('St. Louis Premium Peche');
INSERT INTO BEER (name) VALUES ('Straffe Hendrik Quadrupel');
INSERT INTO BEER (name) VALUES ('Straffe Hendrik Tripel');
INSERT INTO BEER (name) VALUES ('Surfine');
INSERT INTO BEER (name) VALUES ('Stille Nacht');
INSERT INTO BEER (name) VALUES ('Special Extra Export Stout');
INSERT INTO BEER (name) VALUES ('The Wipers Times 14');
INSERT INTO BEER (name) VALUES ('Timmermans Kriek Lambicus');
INSERT INTO BEER (name) VALUES ('Timmermans Lambicus Blanche');
INSERT INTO BEER (name) VALUES ('Timmermans Oude Gueuze');
INSERT INTO BEER (name) VALUES ('Trignac XII');
INSERT INTO BEER (name) VALUES ('Tripel d’Anvers');
INSERT INTO BEER (name) VALUES ('Tripel Kanunnik');
INSERT INTO BEER (name) VALUES ('Tripel Karmeliet');
INSERT INTO BEER (name) VALUES ('Tripel LeFort');
INSERT INTO BEER (name) VALUES ('Troubadour Blond');
INSERT INTO BEER (name) VALUES ('Troubadour Magma');
INSERT INTO BEER (name) VALUES ('Val-Dieu Blonde');
INSERT INTO BEER (name) VALUES ('Val-Dieu Brune');
INSERT INTO BEER (name) VALUES ('Val-Dieu Cuvée 800');
INSERT INTO BEER (name) VALUES ('Val-Dieu Grand Cru');
INSERT INTO BEER (name) VALUES ('Val-Dieu Triple');
INSERT INTO BEER (name) VALUES ('Valeir Extra');
INSERT INTO BEER (name) VALUES ('VanderGhinste Roodbruin');
INSERT INTO BEER (name) VALUES ('Vedett Extra Blond');
INSERT INTO BEER (name) VALUES ('Vedett Extra IPA');
INSERT INTO BEER (name) VALUES ('Vedett Extra White');
INSERT INTO BEER (name) VALUES ('Waterloo Cuvée Impériale');
INSERT INTO BEER (name) VALUES ('Waterloo Récolte');
INSERT INTO BEER (name) VALUES ('Waterloo Strong Dark');
INSERT INTO BEER (name) VALUES ('Waterloo Triple Blond');
INSERT INTO BEER (name) VALUES ('Waterloo Triple Hop');
INSERT INTO BEER (name) VALUES ('Westmalle Dubbel');
INSERT INTO BEER (name) VALUES ('Westmalle Tripel');
INSERT INTO BEER (name) VALUES ('Westvleteren 12 (XII)');
INSERT INTO BEER (name) VALUES ('Westvleteren 8');
INSERT INTO BEER (name) VALUES ('Westvleteren Blond');
INSERT INTO BEER (name) VALUES ('Wieze');
INSERT INTO BEER (name) VALUES ('Wilderen Goud');
INSERT INTO BEER (name) VALUES ('Wilderen Kriek');
INSERT INTO BEER (name) VALUES ('Wild Jo');